### ISSUE TITLE
MetadataTypeAttribute ignored in latest version

### ISSUE THREAD

**Issue by georgemak** [JamesNK/Newtonsoft.Json#405]
I am not really sure if this is a bug or the functionality has changed in the latest versions but after updating a web api project from Newtonsoft.Json version 4.5.11 to version 6.0.6 I discovered that the annotations were actually ignored and the serialization occured even for the properties that were annotated as JsonIgnore. 

In order to annotate the objects I use buddy classes:

    [MetadataType(typeof(CustomerValidation))]
    public partial class Customer
    {
    
    public class CustomerValidation
    {
        [JsonIgnore]
        public System.Guid UpdatedBy_Id { get; set; }
    }
    }

If this is not a bug, how can the same functionality be accomplished in the latest version?

**Comment by JamesNK** [comment]
I think I might have fixed it for realz this time. I know at least I've fixed the scenario @Paulskit has.

**Comment by JamesNK** [comment]
I have released a new version. @Paulskit your issue should be fixed. I don't know about anyone else's but if you could check then that would be super.

**Comment by istvanpuskas** [comment]
Unfortunately not. The simplest scenario is the code that @paulduran commented. The 'Gender' property is still seems serialized. I wrote a really simple console application to test it (with 6.0.8 from nuget). Actually the value of the field is null, which suggests reflection finds the property defined in the base class.

using Newtonsoft.Json;

namespace jsonnet_cs_test
{
    class Base
    {
        public string prop1 { get; set; }
    }

    class Derived: Base
    {
        [JsonIgnore]
        public new string prop1 { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            System.Console.WriteLine(JsonConvert.SerializeObject(new Derived { prop1 = "x" }));
            //output: {"prop1":null}

            System.Console.ReadKey();
        }
    }
}

**Comment by JamesNK** [comment]
You and @paulduran are talking about a separate bug that looks like it has been around for more than a year and a half. Could you make a new issue for it?

**Comment by JamesNK** [comment]
Is anyone still broken with MetadataTypeAttribute problems that have popped up between releases? Speak now or I'll close this issue.

**Comment by philbern** [comment]
I do still have this exact problem with version 6.0.8 on .net 4.5.1 and mvc web api 5.2.2

Also, setting ProxyCreationEnabled to false doesnt fix it

**Comment by JamesNK** [comment]
You'll need to upload an example project somewhere. Something that I can just F5 an run to see the issue. Without being able to see it I can't fix it.

**Comment by philbern** [comment]
Here's a simplified project reproducing the problem:
https://dl.dropboxusercontent.com/u/31808436/TestJsonNet.zip

You just need to restore de nuget packages and press F5

As you will see, the problem seems related to the use of OData Expand instruction

**Comment by MaxAnikin** [comment]
Hello, I see the same issue with the version 6.0.8. JsonIgnore attribute is not working at all. Simple class with a few properties and some of them marked with JsonIgnore. Result json string contains all the properties.

**Comment by JamesNK** [comment]
Is it related to metadatatypeattribute? If not then create a new issue and include your class + json.

**Comment by SpiegelSoft** [comment]
I am seeing the same issue when using Json.NET and OData.  JsonIgnore is being ignored.

**Comment by JamesNK** [comment]
@philbern I tested your code with an old version of Json.NET and the result was the same. This isn't a regression. OData is turning the object that gets passed to Json.NET into a dictionary which means it has no knowledge of the attributes.

**Comment by JamesNK** [comment]
I'm closing this. I'm fairly certain I have fixed the regression.

**Comment by Paulskit** [comment]
Sorry for delay. Yes, issue is fixed for my scenario. Thanks.
